version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Construyendo imagen..."
      - docker build -t mi-app .
      - echo "Generando log..."
      - docker run --name contenedor-prueba mi-app
  post_build:
    commands:
      - echo "Extrayendo log..."
      - docker cp contenedor-prueba:/app/backup.log .
      - echo "Subiendo a S3..."
      # Quitamos el ACL temporalmente para verificar que el permiso de IAM funcione
      - aws s3 cp backup.log s3://actividad15bucket/backup.log
      - echo "¡Listo!"