version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando Docker...
  build:
    commands:
      - echo Construyendo la imagen de Docker...
      - docker build -t mi-app .
      - echo Ejecutando el contenedor para generar el log...
      - docker run --name contenedor-prueba mi-app
  post_build:
    commands:
      - echo Extrayendo el archivo backup.log del contenedor...
      - docker cp contenedor-prueba:/app/backup.log .
      - echo Subiendo el archivo a S3...
      - aws s3 cp backup.log s3://actividad15bucket/ --acl bucket-owner-full-control
      - echo Proceso terminado con éxito.